// Authentication Actions Constants

const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT = "LOGOUT"
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAILURE = "REGISTER_FAILURE";
const CLEAR_ERROR = "CLEAR_ERROR";

// Workout Plan Actions Constants

const FREQUENCY_CHANGE = "FREQUENCY_CHANGE";
const SESSION_DAY_CHANGE = "SESSION_DAY_CHANGE";
const ADD_SESSION_EXERCISE = "ADD_SESSION_EXERCISE";

export {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  REGISTER_SUCCESS,
  REGISTER_FAILURE,
  CLEAR_ERROR,
  FREQUENCY_CHANGE,
  SESSION_DAY_CHANGE,
  ADD_SESSION_EXERCISE
}